### ISSUE TITLE
Rolls break scrolling

### ISSUE THREAD

**Issue by Rinoka** [relick/FoundryVTT-Chat-Scrolling#2]
If the latest message was a roll, it won't scroll.

Doesn't work with Better Rolls. Haven't tested with others. If you can't replicate, let me know, I'll try to isolate the incompatibility.

**Comment by relick** [comment]
Using just Foundy 0.7.9, 5e 1.2.0, Better Rolls 1.2.2 and Chat Scrolling 0.0.8, I'm not able to reproduce. It sounds like there may be a conflict with another module though, so if you're able to narrow down which it is I can take a look at fixing it. Thanks!

**Comment by relick** [comment]
closing as inactive, if anyone runs into the same problem please create a new issue
